class MapData(object):
    def __init__(self,position):
        self.grass = []
        self.trees = []
        self.ledges = []
        self.warps = []
        self.players = []

class Tree(object):
    def __init__(self,position):
        self.position = position

class OpenSpace(object):
    def __init__(self,position):
        self.position = position

class Grass(object):
    def __init__(self,position):
        self.position = position

class Ledge(object):
    def __init__(self,position):
        self.position = position

class Warp(object):
    def __init__(self,position):
        self.position = position

viridianCenterMap = [
'                    ',
'                    ',
'                    ',
'                    ',
'     mMUIwwwwmM     ',
'     mMJK+   mM     ',
'     mrttRrttyM     ',
'     m        M     ',
'     m        M     ',
'     mPP    PPM     ',
'     mpp    ppM     ',
'     mWWWddWWWM     ',
'                    ',
'                    ',
'                    ',
'                    '
]

oakLabMap = [
'                    ',
'                    ',
'                    ',
'                    ',
'    mwwwwwwwwwwM    ',
'    mryry  ccccM    ',
'    m     0    M    ',
'    mUI  ^ OqQ M    ',
'    mJK        M    ',
'    m          M    ',
'    mcccc??ccccM    ',
'    m          M    ',
'    m          M    ',
'    m          M    ',
'    mWWWWddWWWWM    ',
'                    ',
'                    ',
'                    ',
'                    '
]

palletTownMap = [
'@@@@@@@@@    @%%@    @@@@@@@',
'@@@@@@@@@    @%%@    @@@@@@@',
'@@@@@@@@@    @%%@    @@@@@@@',
'@@@@@@@@@@@@@@%%@@@@@@@@@@@@',
'@@@@@@@@@@@@@@%%@@@@@@@@@@@@',
'@@@@@@@@@@@@@@%%@@@@@@@@@@@@',
'@@@@@@@@@@@@@@%%@@@@@@@@@@@@',
'@@@@@         ??       @@@@@',
'@@@@@   {__}    {__}   @@@@@',
'@@@@@ gg[--]  gg[--]   @@@@@',
'@@@@@ gS[D-]  gS[D-]   @@@@@',
'@@@@@                  @@@@@',
'@@@@@                  @@@@@',
'@@@@@   gggg  {____}   @@@@@',
'@@@@@   bbbS  [----]   @@@@@',
'@@@@@         [-D--]   @@@@@',
'@@@@@         gggggggg @@@@@',
'@@@@@   ~~~~  bbbSbbgg @@@@@',
'@@@@@   ~~~~           @@@@@',
'@@@@@   ~~~~*          @@@@@',
'@@@@@   ~~~~           @@@@@',
'@@@@@@@@~~~~@@@@@@@@@@@@@@@@',
'@@@@@@@@~~~~@@@@@@@@@@@@@@@@',
'@@@@@@@@~~~~@@@@@@@@@@@@@@@@',
'@@@@@@@@~~~~@@@@@@@@@@@@@@@@',
]

routeOneMap = [
'     b    b  b    b     ',
'     b    b  b    b     ',
'     b    b  b    b     ',
'     b    b  b    b     ',
'     b    b  b    b     ',
'     b    b  b    b     ',
'@@@@@@@@@@@  @@@@@@@@@@@',
'@@@@@              @@@@@',
'@@@@@              @@@@@',
'@@@@@     @        @@@@@',
'@@@@@=====@====    @@@@@',
'@@@@@     @%%%%%%%%@@@@@',
'@@@@@     @%%%%%%%%@@@@@',
'@@@@@     @%%%%%%%%@@@@@',
'@@@@@=====@%%%%%%%%@@@@@',
'@@@@@              @@@@@',
'@@@@@              @@@@@',
'@@@@@          %%%%@@@@@',
'@@@@@@@====@@@@%%%%@@@@@',
'@@@@@          %%%%@@@@@',
'@@@@@          %%%%@@@@@',
'@@@@@              @@@@@',
'@@@@@              @@@@@',
'@@@@@              @@@@@',
'@@@@@= === ========@@@@@',
'@@@@@              @@@@@',
'@@@@@              @@@@@',
'@@@@@        %%%%  @@@@@',
'@@@@@@@@@@@@@%%%%==@@@@@',
'@@@@@        %%%%  @@@@@',
'@@@@@        %%%%  @@@@@',
'@@@@@              @@@@@',
'@@@@@==   =========@@@@@',
'@@@@@  %%%%    %%%%@@@@@',
'@@@@@  %%%%    %%%%@@@@@',
'@@@@@%%%%    %%%%  @@@@@',
'@@@@@%%%%    %%%%  @@@@@',
'@@@@@@@@@@@%%@@@@@@@@@@@',
'@@@@@     @%%@     @@@@@',
'@@@@@     @%%@     @@@@@',
'@@@@@     @%%@     @@@@@',
'@@@@@@@@@@@%%@@@@@@@@@@@',
'@@@@@@@@@@@%%@@@@@@@@@@@',
'@@@@@@@@@@@%%@@@@@@@@@@@',
'@@@@@@@@@@@%%@@@@@@@@@@@',
'@@@@@@@@@@@@@@@@@@@@@@@@'
]

viridianCityMap = [
'@@@@@@@@@@@@@@@@@@@@b  @@@@@@@@@@@@@@@@@@@@@@',
'@@@@@@@@@@@@@@@@@@@@b  @@@@@@@@@@@@@@@@@@@@@@',
'@@@@@@@@@@@@@@@@@@@@b  @@@@@@@@@@@@@@@@@@@@@@',
'@@@@@@@@@@@@@@@@@@@@b  @@@@@@@@@@@@@@@@@@@@@@',
'BBBBBBBBBL@@@@@@@@@@b  @@@@@@@@@@@@@@@@@@@@@@',
'BBBBBBBBBL@@@@@@@@@@b  @@@@@@@@@@@@@@@@@@@@@@',
'BBBBBBBBBL@@@@@@@@@@b  S@@@@            @@@@@',
'BBBBBBBBBL@@@@@@@@@@b   @@@@            @@@@@',
'BBBBBBBBBL                      {____}  @@@@@',
'BBBBBBBBBL  bbbbbb@@            [----]  @@@@@',
'BBBBBBBBBL b@@@@@@@@b   b       [--G-]  @@@@@',
'BBBBBBBBBL b@@@@@@@@b   b      S[hDhh]  @@@@@',
'BBBBBBBBBL b@@@@@@@@b   {__}============@@@@@',
'BBBBBBBBBL b@@@@@@@@b   [D-]            @@@@@',
'BBBBBBBBBL b@@@@@@@@b                   @@@@@',
'BBBBBBBBBL b@@@@@@@@b                   @@@@@',
'LLLLLLLLLL b@@@@@@@@b   bbbbbbbbbbbbbbbb@@@@@',
'    L      b@@@@@@@@b   {__}            @@@@@',
'    !      b@@@@@@@@b   [D-]            @@@@@',
'    !       @@@@@@@@            {__}    @@@@@',
'    L                S  bbbb    [--]    @@@@@',
'LLLLLLLL                        [--]    @@@@@',
'BBBBBBBL                        [D$]    @@@@@',
'BBBBBBBL                                @@@@@',
'BBBBBBBL@@@@                            @@@@@',
'BBBBBBBL                  {__}          @@@@@',
'BBBBBBBL    @@            [--]          @@@@@',
'BBBBBBBL    ~~~~~~        [--]          @@@@@',
'BBBBBBBL    ~~~~~~        [D<]          @@@@@',
'BBBBBBBL    ~~~~~~                      @@@@@',
'LLLLLLLL====~~~~~~= === ================@@@@@',
'       b                                @@@@@',
'       b                 S              @@@@@',
'       b                                @@@@@',
'       bbbbbbbbbbbbbbbbb  bbbbbbbbbbbbbb@@@@@',
'                  b    b  b    b        @@@@@',
'                  b    b  b    b        @@@@@',
'                  b    b  b    b        @@@@@',
'                  b    b  b    b        @@@@@',
'@@@@@@@@@@@@@@@@@@@@@@@@  @@@@@@@@@@@@@@@@@@@',
'@@@@@@@@@@@@@@@@@@              @@@@@@@@@@@@@',
'@@@@@@@@@@@@@@@@@@              @@@@@@@@@@@@@'
]


routeTwoMap = [
'@@@@@@@@@@@@  @@@@@@@@@@@@@@',
'@@@@@@@@@@@@  @@@@@@@@@@@@@@',
'@@@@@@@@@@@@  @@@@@@@@@@@@@@',
'@@@@@@@@@@@@  @@@@@@@@@@@@@@',
'@@@@%%%%%%%%  b         @@@@',
'@@@@%%%%%%%%  b         @@@@',
'@@@@%%%%%%%%  b         @@@@',
'@@@@%%%%%%%%  b         @@@@',
'@@@@%%%%%%%%  LLLLLLLL  @@@@',
'@@@@%%%%%%%%  LBBBBBBL  @@@@',
'@@@@          LBBBBBBL  @@@@',
'@@@@          LLLLLLLL  @@@@',
'@@@@@@@ @@@@@@          @@@@',
'@@@@  @ @               @@@@',
'@@@@  {__}              @@@@',
'@@@@  [--]              @@@@',
'@@@@bb[D-]bbbbbbbb      @@@@',
'@@@@        @@@@@@      @@@@',
'@@@@        @@@@@@      @@@@',
'@@@@        @@@@@@      @@@@',
'@@@@        @@@@@@      @@@@',
'@@@@        @@@@@@      @@@@',
'@@@@        @@@@@@      @@@@',
'@@@@@@@@@@@@@@@@@@      @@@@',
'@@@@@@@@@@@@@@@@@@      @@@@',
'@@@@@@@@@@@@@@@@@@      @@@@',
'@@@@@@@@@@@@@@@@@@      @@@@',
'@@@@@@@@@@@@@@@@@@      @@@@',
'@@@@@@@@@@@@@@@@@@      @@@@',
'@@@@@@@@@@@@@@@@@@      @@@@',
'@@@@@@@@@@@@@@@@@@      @@@@',
'@@@@@@@@@@@@@@@@@@      @@@@',
'@@@@@@@@@@@@@@@@@@      @@@@',
'@@@@@@@@@@@@@@@@@@      @@@@',
'@@@@@@@@@@@@@@@@@@      @@@@',
'@@@@@@@@@@@@@@@@@@      @@@@',
'@@@@@@@@@@@@@@@@@@      @@@@',
'@@@@@@@@@@@@@@@@@@      @@@@',
'@@@@@@@@@@@@@@@@@@      @@@@',
'@@@@  @ @@@@@@@@@@      @@@@',
'@@@@  @ @     @@@@      @@@@',
'@@@@  {__}    @@@@      @@@@',
'@@@@  [--]    @@@@      @@@@',
'@@@@bb[D-]bbbb@@@@= ====@@@@',
'@@@@           @        @@@@',
'@@@@           @        @@@@',
'@@@@           @        @@@@',
'@@@@========   @        @@@@',
'@@@@    %%%%%% @        @@@@',
'@@@@    %%%%%% @=== ====@@@@',
'@@@@    %%%%%% @        @@@@',
'@@@@    %%%%%% @        @@@@',
'@@@@            @       @@@@',
'@@@@      @@@@@@@@      @@@@',
'@@@@     @@@@@@@@       @@@@',
'@@@@     @@@@@@@@       @@@@',
'@@@@      @@@@@@@       @@@@',
'@@@@            @       @@@@',
'@@@@            @       @@@@',
'@@@@            @       @@@@',
'@@@@@@          @       @@@@',
'@@@@@@===== ====@@= ====@@@@',
'@@@@@@          @       @@@@',
'@@@@@@          @       @@@@',
'@@@@@@          @       @@@@',
'@@@@@@    S     @       @@@@',
'@@@@@@          @       @@@@',
'@@@@@@          @       @@@@',
'@@@@@@          @       @@@@',
'@@@@@@       @@@@@@@@@@@@@@@',
'@@@@@@@@@@b  @@@@@@@@@@@@@@@',
'@@@@@@@@@@b  @@@@@@@@@@@@@@@',
'@@@@@@@@@@b  @@@@@@@@@@@@@@@',
'@@@@@@@@@@b  @@@@@@@@@@@@@@@',
'@@@@@@@@@@b  S@@@@@@@@@@@@@@',
'@@@@@@@@@@b   @@@@@@@@@@@@@@',
'@@@@@@@@@@b   @@@@@@@@@@@@@@'
]

viridianForestEntrance = [
'                    ',
'                    ',
'                    ',
'                    ',
'     mwwwDDwwwM     ',
'     mPP    PPM     ',
'     mpp    ppM     ',
'     m        M     ',
'     m        M     ',
'     mPP    PPM     ',
'     mpp    ppM     ',
'     mWWWddWWWM     ',
'                    ',
'                    ',
'                    ',
'                    '
]

viridianForestMap = [
'                                          ',
'                                          ',
'                                          ',
'    wDDw                                  ',
'    T  TuiTTTTTTTTuiTTTTTTTTTTTTTTTTTT    ',
'    T STjk   *    jk           *     T    ',
'    T  Tui        ui                 T    ',
'    T  Tjk        jk    TTTTTTTTTT   T    ',
'    T  Tui   TT   ui   TuiuiuiuiuiT  T    ',
'    T  Tjk   TT   jk   TjkjkjkjkjkT  T    ',
'    T%%Tui%%%TT%%%ui%%%TuiuiuiuiuiT  T    ',
'    T%%Tjk%%%TT%%%jk%%%TjkjkjkjkjkT  T    ',
'    T%%Tui%%%TT%%%ui%%%%%%%%         T    ',
'    T%%Tjk%%%TT%%%jk%%%%%%%%         T    ',
'    T%%Tui%%%TT%%%ui%%%TuiuiT  Tui%%%T    ',
'    T%%Tjk%%%TT%%%jk%%%TjkjkT  Tjk%%%T    ',
'    T%%Tui%%%TT%%%ui%%%TuiuiT  Tui%%%T    ',
'    T%%Tjk%%%TT%%%jk%%%TjkjkT  Tjk%%%T    ',
'    T%%Tui%%%TT%%%ui%%%TuiuiT  Tui%%%T    ',
'    T%%Tjk%%%TT%%%jk%%%TjkjkT  Tjk%%%T    ',
'    T%%Tui%%%TT%%%  %%%TuiuiT  Tui%%%T    ',
'    T%%Tjk%%%TT%%%  %%%TjkjkT STjk%%%T    ',
'    T%%Tui%%%TT        TuiuiT        T    ',
'    T%*Tjk%%%TT        TjkjkT      * T    ',
'    T%%Tui%%%TuiuiuiuiuiuiuiT%%%uiT  T    ',
'    T%%Tjk%%%TjkjkjkjkjkjkjkT%%%jkT  T    ',
'    T%%%  %%%TuiuiuiuiuiuiuiT%%%uiT  T    ',
'    T%%%  %%%TjkjkjkjkjkjkjkT%%%jkT  T    ',
'    T   S        TuiuiuiuiuiT%%%uiT  T    ',
'    T            TjkjkjkjkjkT%%%jkT  T    ',
'    uiuiuiuiuiT  TuiuiuiuiuiT%%%uiT  T    ',
'    jkjkjkjkjkT  TjkjkjkjkjkT%%%jkT  T    ',
'    uiuiuiuiuiT  TuiuiuiuiuiT%%%uiT  T    ',
'    jkjkjkjkjkT  TjkjkjkjkjkT%%%jkT  T    ',
'    T%%%%%%%%TuiuiuiuiuiuiuiT%%%uiT  T    ',
'    T%%%%%%%%TjkjkjkjkjkjkjkT%%%jkT  T    ',
'    uiuiui  %%%%%%%%S %TuiuiT%       T    ',
'    jkjkjk  %%%%%%%%  %TjkjkT%   *   T    ',
'    uiuiui  %TuiuiT%  %TuiuiT%  uiuiui    ',
'    jkjkjk  %TjkjkT%  %TjkjkT%  jkjkjk    ',
'    uiuiui  %TuiuiT%  %TuiuiT%  uiuiui    ',
'    jkjkjk  %TjkjkT%  %TjkjkT%  jkjkjk    ',
'    uiuiui  %TuiuiT%  %TuiuiT%  uiuiui    ',
'    jkjkjk  %TjkjkT%  %TjkjkT%  jkjkjk    ',
'    T%%%%%  %%%%%%%%  %%%%%%%%  %%%%%T    ',
'    T%%%%%  %%%%%%%%ui%%%%%%%%  %%%%%T    ',
'    T%%%%%          jk          %%%%%T    ',
'    T%%%%%                      %%%%%T    ',
'    uiuiuiuiuiuiuiT    Tuiuiuiuiuiuiui    ',
'    jkjkjkjkjkjkjkT    Tjkjkjkjkjkjkjk    ',
'    uiuiuiuiuiuiuiT    Tuiuiuiuiuiuiui    ',
'    jkjkjkjkjkjkjkTTddTTjkjkjkjkjkjkjk    ',
'                                          ',
'                                          ',
'                                          ',
'                                          '
]

viridianForestExit = [
'                    ',
'                    ',
'                    ',
'                    ',
'     mwwwDDwwwM     ',
'     mPP    PPM     ',
'     mpp    ppM     ',
'     m        M     ',
'     m        M     ',
'     mPP    PPM     ',
'     mpp    ppM     ',
'     mWWWddWWWM     ',
'                    ',
'                    ',
'                    ',
'                    '
]

pewterCity = [
'gggggbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb@@@@@@',
'BBBBL  gggg{______}{____}ggggggggggg@@@@@',
'BBBBL  gggg[______][____]@@@@ggggggg@@@@@',
'BBBBL  gggg[______][----]ggggggggggg@@@@@',
'BBBBL  gggg[______][Dhhh]gg@@ggggggg@@@@@',
'BBBBL  gggg[------]  ggggggg@ggggggg@@@@@',
'BBBBL=== ==[hhhhDh]=========@=======@@@@@',
'BBBBL                               @@@@@',
'BBBBL                               @@@@@',
'BBBBL  gggggggggggg                LBBBBB',
'BBBBL  gggggggggggg                LBBBBB',
'BBBBL                gggggggg{__}  LBBBBB',
'BBBBL                gggggggg[D-]  LBBBBB',
'BBBBL  gggg  {____}    {__}        LBBBBB',
'BBBBL  gggg  [----]    [--]        LBBBBB',
'BBBBL  gggg  [--G-]  gg[--]gggggg  @     ',
'BBBBL  gggg S[---D]  gg[D$]gggggg  @     ',
'BBBBL              @               @     ',
'BBBBL              @              S@     ',
'BBBBL  gggg  gggggg@ gggggggggggg  LBBBBB',
'BBBBL@@@@@@@@@@@@@@@ gggggggggggg  LBBBBB',
'BBBBL        {__}                  LBBBBB',
'BBBBL        [--]      @@@S@@@@    LBBBBB',
'BBBBL  gggggg[--]gg  g@gggggggg@g  LBBBBB',
'BBBBL  gggggg[D<]gg  g@gggggggg@g  LBBBBB',
'BBBBL                g@gggggggg@g  gbgggg',
'BBBBL                g@gggggggg@g  gbgggg',
'BBBBL  {__}gggggggg  g@gggggggg@g  gbgggg',
'BBBBL  [D-]gggggggg Sg@=== ====@g  gbgggg',
'BBLbb                              gbgggg',
'BBLbb                              gbgggg',
'BBLbbbbbbbbbb@@@@@@  @@@@@@bbbbbbbbbbgggg',
'LLLgggggggggg@@@@@@  @@@@@@gggggggggggggg',
'ggggggggggggg@@@@@@  @@@@@@gggggggggggggg',
'ggggggggggggg%%%%%%  b     gggggggggggggg',
'ggggggggggggg%%%%%%  b     gggggggggggggg',
'ggggggggggggg%%%%%%  b     gggggggggggggg'
]

pewterCenterMap = [
'                    ',
'                    ',
'                    ',
'                    ',
'     mMUIwwwwmM     ',
'     mMJK+   mM     ',
'     mrttRrttyM     ',
'     m        M     ',
'     m        M     ',
'     mPP    PPM     ',
'     mpp    ppM     ',
'     mWWWddWWWM     ',
'                    ',
'                    ',
'                    ',
'                    '
]

locationMapDict = {'Oak Lab': oakLabMap, 'Pallet Town': palletTownMap, 'Route 1': routeOneMap, 'Viridian City': viridianCityMap, 'Viridian Center': viridianCenterMap, 'Route 2': routeTwoMap, 'Viridian Forest': viridianForestMap, 'Viridian Forest Entrance': viridianForestEntrance, 'Viridian Forest Exit': viridianForestExit, 'Pewter City': pewterCity, 'Pewter Center': pewterCenterMap}

#locationMapDict = {'Pallet Town': palletTownMap, 'Route 1': routeOneMap, 'Route 2': routeTwoMap, 'Viridian City': viridianCityMap, 'Viridian Forest': viridianForestMap, 'Route 22': routeTwentyTwoMap, 'Pewter City': pewterCityMap}
