bulbasaurPossibleMovesByLevel = {1:'Tackle',2:'Growl',7:'Leech Seed',13:'Vine Whip',20:'Poison Powder',27:'Razor Leaf',34:'Growth',41:'Sleep Powder',48:'Solar Beam'}
ivysaurPossibleMovesByLevel = {1:'Tackle',2:'Growl',7:'Leech Seed',13:'Vine Whip',22:'Poison Powder',30:'Razor Leaf',38:'Growth',46:'Sleep Powder',54:'Solar Beam'}
venusaurPossibleMovesByLevel = {1:'Tackle',2:'Growl',7:'Leech Seed',13:'Vine Whip',22:'Poison Powder',30:'Razor Leaf',43:'Growth',55:'Sleep Powder',65:'Solar Beam'}
charmanderPossibleMovesByLevel = {1:'Scratch',2:'Growl',9:'Ember',15:'Leer',22:'Rage',30:'Slash',38:'Flamethrower',46:'Fire Spin'}
charmeleonPossibleMovesByLevel = {1:'Scratch',2:'Growl',9:'Ember',15:'Leer',24:'Rage',33:'Slash',42:'Flamethrower',56:'Fire Spin'}
charizardPossibleMovesByLevel = {1:'Scratch',2:'Growl',9:'Ember',15:'Leer',24:'Rage',36:'Slash',46:'Flamethrower',55:'Fire Spin'}
squirtlePossibleMovesByLevel = {1:'Tackle',2:'Tail Whip',8:'Bubble',15:'Water Gun',22:'Bite',28:'Withdraw',35:'Skull Bash',42:'Hydro Pump'}
wartortlePossibleMovesByLevel = {1:'Tackle',2:'Tail Whip',8:'Bubble',15:'Water Gun',24:'Bite',31:'Withdraw',39:'Skull Bash',47:'Hydro Pump'}
blastoisePossibleMovesByLevel = {1:'Tackle',2:'Tail Whip',8:'Bubble',15:'Water Gun',24:'Bite',31:'Withdraw',42:'Skull Bash',52:'Hydro Pump'}
caterpiePossibleMovesByLevel = {1:'Tackle',2:'String Shot'}
metapodPossibleMovesByLevel = {1:'Harden'}
butterfreePossibleMovesByLevel = {1:'Tackle',2:'String Shot',3:'Harden',12:'Confusion',15:'Poison Powder',16:'Stun Spore',17:'Sleep Powder',21:'Supersonic',26:'Whirlwind',32:'Psybeam'}
weedlePossibleMovesByLevel = {1:'Poison Sting',2:'String Shot'}
kakunaPossibleMovesByLevel = {1:'Harden'}
beedrillPossibleMovesByLevel = {1:'Poison Sting',2:'String Shot',3:'Harden',12:'Fury Attack',16:'Focus Energy',20:'Twineedle',25:'Rage',30:'Pin Missile',35:'Agility'}
pidgeyPossibleMovesByLevel = {1:'Gust',5:'Sand Attack',12:'Quick Attack',19:'Whirlwind',28:'Wing Attack',36:'Agility',44:'Mirror Move'}
pidgeottoPossibleMovesByLevel = {1:'Gust',5:'Sand Attack',12:'Quick Attack',21:'Whirlwind',31:'Wing Attack',40:'Agility',49:'Mirror Move'}
pidgeotPossibleMovesByLevel = {1:'Gust',5:'Sand Attack',12:'Quick Attack',21:'Whirlwind',31:'Wing Attack',44:'Agility',54:'Mirror Move'}
rattataPossibleMovesByLevel = {1:'Tackle',2:'Tail Whip',7:'Quick Attack',14:'Hyper Fang',23:'Focus Energy',34:'Super Fang'}
raticatePossibleMovesByLevel = {1:'Tackle',2:'Tail Whip',7:'Quick Attack',14:'Hyper Fang',27:'Focus Energy',41:'Super Fang'}
spearowPossibleMovesByLevel = {1:'Peck',2:'Growl',9:'Leer',15:'Fury Attack',22:'Mirror Move',29:'Drill Peck',36:'Agility'}
fearowPossibleMovesByLevel = {1:'Peck',2:'Growl',9:'Leer',15:'Fury Attack',25:'Mirror Move',34:'Drill Peck',43:'Agility'}
ekansPossibleMovesByLevel = {1:'Wrap',2:'Leer',10:'Poison Sting',17:'Bite',24:'Glare',31:'Screech',38:'Acid'}
arbokPossibleMovesByLevel = {1:'Wrap',2:'Leer',10:'Poison Sting',17:'Bite',27:'Glare',36:'Screech',47:'Acid'}
pikachuPossibleMovesByLevel = {1:'Thundershock',2:'Growl',9:'Thunder Wave',16:'Quick Attack',26:'Swift',33:'Agility',43:'Thunder'}
raichuPossibleMovesByLevel = {1:'Thundershock',2:'Growl',9:'Thunder Wave',16:'Quick Attack',26:'Swift',33:'Agility',43:'Thunder'}
sandshrewPossibleMovesByLevel = {1:'Scratch',10:'Sand Attack',17:'Slash',24:'Poison Sting',31:'Swift',38:'Fury Swipes'}
sandslashPossibleMovesByLevel = {1:'Scratch',10:'Sand Attack',17:'Slash',27:'Poison Sting',36:'Swift',47:'Fury Swipes'}
nidoranMPossibleMovesByLevel = {1:'Growl',2:'Tackle',8:'Scratch',14:'Poison Sting',21:'Tail Whip',29:'Bite',36:'Fury Swipes',43:'Double Kick'}
nidorinaPossibleMovesByLevel = {1:'Growl',2:'Tackle',8:'Scratch',14:'Poison Sting',23:'Tail Whip',32:'Bite',41:'Fury Swipes',50:'Double Kick'}
nidoqueenPossibleMovesByLevel = {1:'Growl',2:'Tackle',8:'Scratch',14:'Poison Sting',22:'Tail Whip',23:'Body Slam',32:'Bite',41:'Fury Swipes',50:'Double Kick'}
nidoranFPossibleMovesByLevel = {1:'Leer',2:'Tackle',8:'Horn Attack',14:'Poison Sting',21:'Focus Energy',29:'Fury Attack',36:'Horn Drill',43:'Double Kick'}
nidorinoPossibleMovesByLevel = {1:'Leer',2:'Tackle',8:'Horn Attack',14:'Poison Sting',23:'Focus Energy',32:'Fury Attack',41:'Horn Drill',50:'Double Kick'}
nidokingPossibleMovesByLevel = {1:'Leer',2:'Tackle',8:'Horn Attack',14:'Poison Sting',23:'Thrash',32:'Fury Attack',41:'Horn Drill',50:'Double Kick'}
clefairyPossibleMovesByLevel = {1:'Pound',2:'Growl',13:'Sing',18:'Doubleslap',24:'Minimize',31:'Metronome',39:'Defense Curl',48:'Light Screen'}
clefablePossibleMovesByLevel = {1:'Pound',2:'Growl',13:'Sing',18:'Doubleslap',24:'Minimize',31:'Metronome',39:'Defense Curl',48:'Light Screen'}
vulpixPossibleMovesByLevel = {1:'Ember',2:'Tail Whip',16:'Quick Attack',21:'Roar',28:'Confuse Ray',35:'Flamethrower',42:'Fire Spin'}
ninetalesPossibleMovesByLevel = {1:'Ember',2:'Tail Whip',16:'Quick Attack',21:'Roar',28:'Confuse Ray',35:'Flamethrower',42:'Fire Spin'}
jigglypuffPossibleMovesByLevel = {1:'Sing',9:'Pound',14:'Disable',19:'Defense Curl',24:'Doubleslap',29:'Rest',34:'Body Slam',39:'Double Edge'}
wigglytuffPossibleMovesByLevel = {1:'Sing',9:'Pound',14:'Disable',19:'Defense Curl',24:'Doubleslap',29:'Rest',34:'Body Slam',39:'Double Edge'}
zubatPossibleMovesByLevel = {1:'Leech Life',10:'Supersonic',15:'Bite',21:'Confuse Ray',28:'Wing Attack',36:'Haze'}
golbatPossibleMovesByLevel = {1:'Leech Life',10:'Supersonic',15:'Bite',21:'Confuse Ray',32:'Wing Attack',43:'Haze'}
oddishPossibleMovesByLevel = {1:'Absorb',15:'Poison Powder',17:'Stun Spore',19:'Sleep Powder',24:'Acid',33:'Petal Dance',46:'Solar Beam'}
gloomPossibleMovesByLevel = {1:'Absorb',15:'Poison Powder',17:'Stun Spore',19:'Sleep Powder',28:'Acid',38:'Petal Dance',52:'Solar Beam'}
vileplumePossibleMovesByLevel = {1:'Absorb',15:'Poison Powder',17:'Stun Spore',19:'Sleep Powder',28:'Acid',38:'Petal Dance',52:'Solar Beam'}
parasPossibleMovesByLevel = {1:'Scratch',13:'Stun Spore',20:'Leech Life',27:'Spore',34:'Slash',41:'Growth'}
parasectPossibleMovesByLevel = {1:'Scratch',13:'Stun Spore',20:'Leech Life',27:'Spore',30:'Spore',39:'Slash',48:'Growth'}
venonatPossibleMovesByLevel = {1:'Tackle',2:'Disable',24:'Poison Powder',27:'Leech Life',30:'Stun Spore',35:'Psybeam',38:'Sleep Powder',43:'Psychic'}
venomothPossibleMovesByLevel = {1:'Tackle',2:'Disable',24:'Poison Powder',27:'Leech Life',30:'Stun Spore',38:'Psybeam',43:'Sleep Powder',50:'Psychic'}
diglettPossibleMovesByLevel = {1:'Scratch',15:'Growl',19:'Dig',24:'Sand Attack',31:'Slash',40:'Earthquake'}
dugtrioPossibleMovesByLevel = {1:'Scratch',15:'Growl',19:'Dig',24:'Sand Attack',35:'Slash',47:'Earthquake'}
meowthPossibleMovesByLevel = {1:'Scratch',2:'Growl',12:'Bite',17:'Pay Day',24:'Screech',33:'Fury Swipes',44:'Slash'}
persianPossibleMovesByLevel = {1:'Scratch',2:'Growl',12:'Bite',17:'Pay Day',24:'Screech',37:'Fury Swipes',51:'Slash'}
psyduckPossibleMovesByLevel = {1:'Scratch',28:'Tail Whip',31:'Disable',36:'Confusion',43:'Fury Swipes',52:'Hydro Pump'}
golduckPossibleMovesByLevel = {1:'Scratch',28:'Tail Whip',31:'Disable',39:'Confusion',48:'Fury Swipes',59:'Hydro Pump'}
mankeyPossibleMovesByLevel = {1:'Scratch',2:'Leer',15:'Karate Chop',21:'Fury Attack',27:'Focus Energy',33:'Seismic Toss',39:'Thrash'}
primeapePossibleMovesByLevel = {1:'Scratch',2:'Leer',15:'Karate Chop',21:'Fury Attack',27:'Focus Energy',37:'Seismic Toss',46:'Thrash'}
growlithePossibleMovesByLevel = {1:'Bite',2:'Roar',18:'Ember',23:'Leer',30:'Take Down',39:'Agility',50:'Flamethrower'}
arcaninePossibleMovesByLevel = {1:'Bite',2:'Roar',18:'Ember',23:'Leer',30:'Take Down',39:'Agility',50:'Flamethrower'}
poliwagPossibleMovesByLevel = {1:'Bubble',16:'Hypnosis',19:'Water Gun',25:'Doubleslap',31:'Body Slam',38:'Amnesia',45:'Hydro Pump'}
poliwhirlPossibleMovesByLevel = {1:'Bubble',16:'Hypnosis',19:'Water Gun',26:'Doubleslap',33:'Body Slam',41:'Amnesia',49:'Hydro Pump'}
poliwrathPossibleMovesByLevel = {1:'Bubble',16:'Hypnosis',19:'Water Gun',26:'Doubleslap',33:'Body Slam',41:'Amnesia',49:'Hydro Pump'}
abraPossibleMovesByLevel = {1:'Teleport'}
kadabraPossibleMovesByLevel = {1:'Teleport',2:'Confusion',20:'Disable',27:'Psybeam',31:'Recover',38:'Psychic',42:'Reflect'}
alakazamPossibleMovesByLevel = {1:'Teleport',2:'Confusion',20:'Disable',27:'Psybeam',31:'Recover',38:'Psychic',42:'Reflect'}
machopPossibleMovesByLevel = {1:'Karate Chop',20:'Low Kick',25:'Leer',32:'Focus Energy',39:'Seismic Toss',46:'Submission'}
machokePossibleMovesByLevel = {1:'Karate Chop',20:'Low Kick',25:'Leer',36:'Focus Energy',44:'Seismic Toss',52:'Submission'}
machampPossibleMovesByLevel = {1:'Karate Chop',20:'Low Kick',25:'Leer',36:'Focus Energy',44:'Seismic Toss',52:'Submission'}
bellsproutPossibleMovesByLevel = {1:'Vine Whip',2:'Growth',13:'Wrap',15:'Poison Powder',18:'Sleep Powder',21:'Stun Spore',26:'Acid',33:'Razor Leaf',42:'Slam'}
weepinbellPossibleMovesByLevel = {1:'Vine Whip',2:'Growth',13:'Wrap',15:'Poison Powder',18:'Sleep Powder',23:'Stun Spore',29:'Acid',38:'Razor Leaf',49:'Slam'}
victreebelPossibleMovesByLevel = {1:'Vine Whip',2:'Growth',13:'Wrap',15:'Poison Powder',18:'Sleep Powder',23:'Stun Spore',29:'Acid',38:'Razor Leaf',49:'Slam'}
tentacoolPossibleMovesByLevel = {1:'Acid',7:'Supersonic',13:'Wrap',18:'Poison Sting',22:'Water Gun',27:'Constrict',33:'Barrier',40:'Screech',48:'Hydro Pump'}
tentacruelPossibleMovesByLevel = {1:'Acid',7:'Supersonic',13:'Wrap',18:'Poison Sting',22:'Water Gun',27:'Constrict',33:'Barrier',35:'Barrier',43:'Screech',50:'Hydro Pump'}
geodudePossibleMovesByLevel = {1:'Tackle',11:'Defense Curl',16:'Rock Throw',21:'Self-Destruct',26:'Harden',31:'Earthquake',36:'Explosion'}
gravelerPossibleMovesByLevel = {1:'Tackle',11:'Defense Curl',16:'Rock Throw',21:'Self-Destruct',29:'Harden',36:'Earthquake',43:'Explosion'}
golemPossibleMovesByLevel = {1:'Tackle',11:'Defense Curl',16:'Rock Throw',21:'Self-Destruct',29:'Harden',36:'Earthquake',43:'Explosion'}
ponytaPossibleMovesByLevel = {1:'Ember',30:'Tail Whip',32:'Stomp',35:'Growl',39:'Fire Spin',43:'Take Down',48:'Agility'}
rapidashPossibleMovesByLevel = {1:'Ember',30:'Tail Whip',32:'Stomp',35:'Growl',39:'Fire Spin',47:'Take Down',55:'Agility'}
slowpokePossibleMovesByLevel = {1:'Confusion',18:'Disable',22:'Head Butt',27:'Growl',33:'Water Gun',40:'Amnesia',48:'Psychic'}
slowbroPossibleMovesByLevel = {1:'Confusion',18:'Disable',22:'Head Butt',27:'Growl',33:'Water Gun',44:'Amnesia',55:'Psychic'}
magnemitePossibleMovesByLevel = {1:'Tackle',21:'Sonic Boom',25:'Thundershock',29:'Supersonic',35:'Thunder Wave',41:'Swift',47:'Screech'}
magnetonPossibleMovesByLevel = {1:'Tackle',21:'Sonic Boom',25:'Thundershock',29:'Supersonic',38:'Thunder Wave',46:'Swift',54:'Screech'}
farfetchdPossibleMovesByLevel = {1:'Peck',2:'Sand Attack',7:'Leer',15:'Fury Attack',23:'Swords Dance',31:'Agility',39:'Slash'}
doduoPossibleMovesByLevel = {1:'Peck',20:'Growl',24:'Fury Attack',30:'Drill Peck',36:'Rage',40:'Tri Attack',44:'Agility'}
dodrioPossibleMovesByLevel = {1:'Peck',20:'Growl',24:'Fury Attack',30:'Drill Peck',39:'Rage',45:'Tri Attack',51:'Agility'}
seelPossibleMovesByLevel = {1:'Head Butt',30:'Growl',35:'Aurora Beam',40:'Rest',45:'Take Down',50:'Ice Beam'}
dewgongPossibleMovesByLevel = {1:'Head Butt',30:'Growl',35:'Aurora Beam',44:'Rest',50:'Take Down',56:'Ice Beam'}
grimerPossibleMovesByLevel = {1:'Pound',2:'Disable',30:'Poison Gas',33:'Minimize',37:'Sludge',42:'Harden',48:'Screech',55:'Acid Armor'}
mukPossibleMovesByLevel = {1:'Pound',2:'Disable',30:'Poison Gas',33:'Minimize',37:'Sludge',45:'Harden',53:'Screech',60:'Acid Armor'}
shellderPossibleMovesByLevel = {1:'Tackle',2:'Withdraw',18:'Supersonic',23:'Clamp',30:'Aurora Beam',39:'Leer',50:'Ice Beam'}
cloysterPossibleMovesByLevel = {1:'Tackle',2:'Withdraw',18:'Supersonic',23:'Clamp',30:'Aurora Beam',39:'Leer',50:'Spike Cannon',51:'Ice Beam'}
gastlyPossibleMovesByLevel = {1:'Lick',2:'Confuse Ray',3:'Night Shade',27:'Hypnosis',35:'Dream Eater'}
haunterPossibleMovesByLevel = {1:'Lick',2:'Confuse Ray',3:'Night Shade',27:'Hypnosis',29:'Hypnosis',38:'Dream Eater'}
gengarPossibleMovesByLevel = {1:'Lick',2:'Confuse Ray',3:'Night Shade',27:'Hypnosis',29:'Hypnosis',38:'Dream Eater'}
onixPossibleMovesByLevel = {1:'Tackle',2:'Screech',15:'Bind',19:'Rock Throw',25:'Rage',33:'Slam',43:'Harden'}
drowzeePossibleMovesByLevel = {1:'Pound',2:'Hypnosis',12:'Disable',17:'Confusion',24:'Head Butt',29:'Poison Gas',32:'Psychic',37:'Meditate'}
hypnoPossibleMovesByLevel = {1:'Pound',2:'Hypnosis',12:'Disable',17:'Confusion',24:'Head Butt',33:'Poison Gas',37:'Psychic',43:'Meditate'}
krabbyPossibleMovesByLevel = {1:'Bubble',2:'Leer',20:'Vice Grip',25:'Guillotine',30:'Stomp',35:'Crab Hammer',40:'Harden'}
kinglerPossibleMovesByLevel = {1:'Bubble',2:'Leer',20:'Vice Grip',25:'Guillotine',30:'Stomp',34:'Stomp',42:'Crab Hammer',49:'Harden'}
voltorbPossibleMovesByLevel = {1:'Tackle',2:'Screech',17:'Sonic Boom',22:'Self-Destruct',29:'Light Screen',36:'Swift',43:'Explosion'}
electrodePossibleMovesByLevel = {1:'Tackle',2:'Screech',17:'Sonic Boom',22:'Self-Destruct',29:'Light Screen',40:'Swift',50:'Explosion'}
exeggcutePossibleMovesByLevel = {1:'Barrage',2:'Hypnosis',25:'Reflect',28:'Leech Seed',32:'Stun Spore',37:'Poison Powder',42:'Solar Beam',48:'Sleep Powder'}
exeggutorPossibleMovesByLevel = {1:'Barrage',2:'Hypnosis',25:'Reflect',27:'Leech Seed',28:'Stomp',32:'Stun Spore',37:'Poison Powder',42:'Solar Beam',48:'Sleep Powder'}
cubonePossibleMovesByLevel = {1:'Bone Club',2:'Growl',25:'Leer',31:'Focus Energy',38:'Thrash',43:'Bonemerang',46:'Rage'}
marowakPossibleMovesByLevel = {1:'Bone Club',2:'Growl',25:'Leer',33:'Focus Energy',41:'Thrash',48:'Bonemerang',55:'Rage'}
hitmonleePossibleMovesByLevel = {1:'Double Kick',2:'Meditate',33:'Rolling Kick',38:'Jump Kick',43:'Focus Energy',48:'High Jump Kick',53:'Mega Kick'}
hitmonchanPossibleMovesByLevel = {1:'Comet Punch',2:'Agility',33:'Fire Punch',38:'Ice Punch',43:'Thunder Punch',48:'Mega Punch',53:'Counter'}
lickitungPossibleMovesByLevel = {1:'Wrap',2:'Supersonic',7:'Stomp',15:'Disable',23:'Defense Curl',31:'Slam',39:'Screech'}
koffingPossibleMovesByLevel = {1:'Tackle',2:'Smog',32:'Sludge',37:'Smokescreen',40:'Self-Destruct',45:'Haze',48:'Explosion'}
weezingPossibleMovesByLevel = {1:'Tackle',2:'Smog',32:'Sludge',39:'Smokescreen',43:'Self-Destruct',49:'Haze',53:'Explosion'}
rhyhornPossibleMovesByLevel = {1:'Horn Attack',30:'Stomp',35:'Tail Whip',40:'Fury Attack',45:'Horn Drill',50:'Leer',55:'Take Down'}
rhydonPossibleMovesByLevel = {1:'Horn Attack',30:'Stomp',35:'Tail Whip',40:'Fury Attack',48:'Horn Drill',55:'Leer',64:'Take Down'}
chanseyPossibleMovesByLevel = {1:'Pound',2:'Doubleslap',24:'Sing',30:'Growl',38:'Minimize',44:'Defense Curl',48:'Light Screen',54:'Double Edge'}
tangelaPossibleMovesByLevel = {1:'Constrict',2:'Bind',29:'Absorb',32:'Poison Powder',36:'Stun Spore',39:'Sleep Powder',45:'Slam',49:'Growth'}
kangaskhanPossibleMovesByLevel = {1:'Comet Punch',2:'Rage',26:'Bite',31:'Tail Whip',36:'Mega Punch',41:'Leer',46:'Dizzy Punch'}
horseaPossibleMovesByLevel = {1:'Bubble',19:'Smokescreen',24:'Leer',30:'Water Gun',37:'Agility',45:'Hydro Pump'}
seadraPossibleMovesByLevel = {1:'Bubble',19:'Smokescreen',24:'Leer',30:'Water Gun',41:'Agility',52:'Hydro Pump'}
goldeenPossibleMovesByLevel = {1:'Peck',2:'Tail Whip',19:'Supersonic',24:'Horn Attack',30:'Fury Attack',37:'Waterfall',45:'Horn Drill',54:'Agility'}
seakingPossibleMovesByLevel = {1:'Peck',2:'Tail Whip',19:'Supersonic',24:'Horn Attack',30:'Fury Attack',39:'Waterfall',48:'Horn Drill',54:'Agility'}
staryuPossibleMovesByLevel = {1:'Tackle',17:'Water Gun',22:'Harden',27:'Recover',32:'Swift',37:'Minimize',42:'Light Screen',47:'Hydro Pump'}
starmiePossibleMovesByLevel = {1:'Tackle',17:'Water Gun',22:'Harden',27:'Recover',32:'Swift',37:'Minimize',42:'Light Screen',47:'Hydro Pump'}
mrMimePossibleMovesByLevel = {1:'Confusion',2:'Barrier',23:'Light Screen',31:'Doubleslap',39:'Meditate',47:'Substitute'}
scytherPossibleMovesByLevel = {1:'Quick Attack',17:'Leer',20:'Focus Energy',24:'Double Team',29:'Slash',35:'Swords Dance',42:'Agility'}
jynxPossibleMovesByLevel = {1:'Pound',2:'Lovely Kiss',15:'Sing',23:'Doubleslap',31:'Ice Punch',39:'Meditate',47:'Blizzard'}
electabuzzPossibleMovesByLevel = {1:'Quick Attack',2:'Leer',34:'Thundershock',37:'Screech',42:'Thunder Punch',49:'Light Screen',54:'Thunder'}
magmarPossibleMovesByLevel = {1:'Ember',36:'Leer',39:'Confuse Ray',43:'Fire Punch',48:'Smokescreen',52:'Smog',55:'Flamethrower'}
pinsirPossibleMovesByLevel = {1:'Vicegrip',25:'Seismic Toss',30:'Guillotine',36:'Focus Energy',43:'Harden',49:'Slash',54:'Swords Dance'}
taurosPossibleMovesByLevel = {1:'Tackle',21:'Stomp',28:'Tail Whip',35:'Leer',44:'Rage',51:'Take Down'}
magikarpPossibleMovesByLevel = {1:'Splash',15:'Tackle'}
gyaradosPossibleMovesByLevel = {1:'Splash',15:'Tackle',20:'Bite',25:'Dragon Rage',32:'Leer',41:'Hydro Pump',52:'Hyper Beam'}
laprasPossibleMovesByLevel = {1:'Water Gun',2:'Growl',16:'Sing',20:'Mist',25:'Body Slam',31:'Confuse Ray',38:'Ice Beam',46:'Hydro Pump'}
dittoPossibleMovesByLevel = {1:'Transform'}
eeveePossibleMovesByLevel = {1:'Tackle',2:'Sand Attack',27:'Quick Attack',31:'Tail Whip',37:'Bite',45:'Take Down'}
vaporeonPossibleMovesByLevel = {1:'Tackle',2:'Sand Attack',27:'Quick Attack',31:'Water Gun',37:'Tail Whip',40:'Bite',42:'Acid Armor',44:'Haze',48:'Mist',54:'Hydro Pump'}
jolteonPossibleMovesByLevel = {1:'Tackle',2:'Sand Attack',27:'Quick Attack',31:'Thundershock',37:'Tail Whip',40:'Thunder Wave',42:'Double Kick',44:'Agility',48:'Pin Missile',54:'Thunder'}
flareonPossibleMovesByLevel = {1:'Tackle',2:'Sand Attack',27:'Quick Attack',31:'Ember',37:'Tail Whip',40:'Bite',42:'Leer',44:'Fire Spin',48:'Rage',54:'Flamethrower'}
porygonPossibleMovesByLevel = {1:'Tackle',2:'Sharpen',2:'Conversion',23:'Psybeam',28:'Recover',35:'Agility',42:'Tri Attack'}
omanytePossibleMovesByLevel = {1:'Water Gun',2:'Withdraw',34:'Horn Attack',39:'Leer',46:'Spike Cannon',53:'Hydro Pump'}
omastarPossibleMovesByLevel = {1:'Water Gun',2:'Withdraw',34:'Horn Attack',39:'Leer',44:'Spike Cannon',49:'Hydro Pump'}
kabutoPossibleMovesByLevel = {1:'Scratch',2:'Harden',34:'Absorb',39:'Slash',44:'Leer',49:'Hydro Pump'}
kabutopsPossibleMovesByLevel = {1:'Scratch',2:'Harden',34:'Absorb',39:'Slash',46:'Leer',53:'Hydro Pump'}
aerodactylPossibleMovesByLevel = {1:'Wing Attack',2:'Agility',33:'Supersonic',38:'Bite',45:'Take Down',54:'Hyper Beam'}
snorlaxPossibleMovesByLevel = {1:'Head Butt',2:'Amnesia',2:'Rest',35:'Body Slam',41:'Harden',48:'Double Edge',56:'Hyper Beam'}
articunoPossibleMovesByLevel = {1:'Peck',2:'Ice Beam',51:'Blizzard',55:'Agility',60:'Mist'}
zapdosPossibleMovesByLevel = {1:'Thundershock',2:'Drill Peck',51:'Thunder',55:'Agility',60:'Light Screen'}
moltresPossibleMovesByLevel = {1:'Peck',2:'Fire Spin',51:'Leer',55:'Agility',60:'Sky Attack'}
dratiniPossibleMovesByLevel = {1:'Wrap',2:'Leer',10:'Thunder Wave',20:'Agility',30:'Slam',40:'Dragon Rage',50:'Hyper Beam'}
dragonairPossibleMovesByLevel = {1:'Wrap',2:'Leer',10:'Thunder Wave',20:'Agility',35:'Slam',45:'Dragon Rage',55:'Hyper Beam'}
dragonitePossibleMovesByLevel = {1:'Wrap',2:'Leer',10:'Thunder Wave',20:'Agility',35:'Slam',45:'Dragon Rage',60:'Hyper Beam'}
mewtwoPossibleMovesByLevel = {1:'Confusion',2:'Disable',2:'Swift',63:'Barrier',66:'Psychic',70:'Recover',75:'Mist',81:'Amnesia'}
mewPossibleMovesByLevel = {1:'Pound',10:'Transform',20:'Mega Punch',30:'Metronome',40:'Psychic'}
