bulbasaurLevelUpMoves = {1:'Tackle',1:'Growl',7:'Leech Seed',13:'Vine Whip',20:'Poison Powder',27:'Razor Leaf',34:'Growth',41:'Sleep Powder',48:'Solar Beam'}
ivysaurLevelUpMoves = {13:'Vine Whip',22:'Poison Powder',30:'Razor Leaf',38:'Growth',46:'Sleep Powder',54:'Solar Beam'}
venusaurLevelUpMoves = {43:'Growth',55:'Sleep Powder',65:'Solar Beam'}
charmanderLevelUpMoves = {1:'Scratch',1:'Growl',9:'Ember',15:'Leer',22:'Rage',30:'Slash',38:'Flamethrower',46:'Fire Spin'}
charmeleonLevelUpMoves = {15:'Leer',24:'Rage',33:'Slash',42:'Flamethrower',56:'Fire Spin'}
charizardLevelUpMoves = {36:'Slash',46:'Flamethrower',55:'Fire Spin'}
squirtleLevelUpMoves = {1:'Tackle',1:'Tail Whip',8:'Bubble',15:'Water Gun',22:'Bite',28:'Withdraw',35:'Skull Bash',42:'Hydro Pump'}
wartortleLevelUpMoves = {15:'Water Gun',24:'Bite',31:'Withdraw',39:'Skull Bash',47:'Hydro Pump'}
blastoiseLevelUpMoves = {24:'Bite',31:'Withdraw',42:'Skull Bash',52:'Hydro Pump'}
caterpieLevelUpMoves = {1:'Tackle',1:'String Shot'}
metapodLevelUpMoves = {1:'Harden'}
butterfreeLevelUpMoves = {12:'Confusion',15:'Poison Powder',16:'Stun Spore',17:'Sleep Powder',21:'Supersonic',26:'Whirlwind',32:'Psybeam'}
weedleLevelUpMoves = {1:'Poison Sting',1:'String Shot'}
kakunaLevelUpMoves = {1:'Harden'}
beedrillLevelUpMoves = {12:'Fury Attack',16:'Focus Energy',20:'Twineedle',25:'Rage',30:'Pin Missile',35:'Agility'}
pidgeyLevelUpMoves = {1:'Gust',5:'Sand Attack',12:'Quick Attack',19:'Whirlwind',28:'Wing Attack',36:'Agility',44:'Mirror Move'}
pidgeottoLevelUpMoves = {21:'Whirlwind',31:'Wing Attack',40:'Agility',49:'Mirror Move'}
pidgeotLevelUpMoves = {44:'Agility',54:'Mirror Move'}
rattataLevelUpMoves = {1:'Tackle',1:'Tail Whip',7:'Quick Attack',14:'Hyper Fang',23:'Focus Energy',34:'Super Fang'}
raticateLevelUpMoves = {14:'Hyper Fang',27:'Focus Energy',41:'Super Fang'}
spearowLevelUpMoves = {1:'Peck',1:'Growl',9:'Leer',15:'Fury Attack',22:'Mirror Move',29:'Drill Peck',36:'Agility'}
fearowLevelUpMoves = {25:'Mirror Move',34:'Drill Peck',43:'Agility'}
ekansLevelUpMoves = {1:'Wrap',1:'Leer',10:'Poison Sting',17:'Bite',24:'Glare',31:'Screech',38:'Acid'}
arbokLevelUpMoves = {17:'Bite',27:'Glare',36:'Screech',47:'Acid'}
pikachuLevelUpMoves = {1:'Thundershock',1:'Growl',9:'Thunder Wave',16:'Quick Attack',26:'Swift',33:'Agility',43:'Thunder'}
raichuLevelUpMoves = {}
sandshrewLevelUpMoves = {1:'Scratch',10:'Sand Attack',17:'Slash',24:'Poison Sting',31:'Swift',38:'Fury Swipes'}
sandslashLevelUpMoves = {27:'Poison Sting',36:'Swift',47:'Fury Swipes'}
nidoranMLevelUpMoves = {1:'Growl',1:'Tackle',8:'Scratch',14:'Poison Sting',21:'Tail Whip',29:'Bite',36:'Fury Swipes',43:'Double Kick'}
nidorinaLevelUpMoves = {14:'Poison Sting',23:'Tail Whip',32:'Bite',41:'Fury Swipes',50:'Double Kick'}
nidoqueenLevelUpMoves = {14:'Poison Sting',23:'Body Slam'}
nidoranFLevelUpMoves = {1:'Leer',1:'Tackle',8:'Horn Attack',14:'Poison Sting',21:'Focus Energy',29:'Fury Attack',36:'Horn Drill',43:'Double Kick'}
nidorinoLevelUpMoves = {23:'Focus Energy',32:'Fury Attack',41:'Horn Drill',50:'Double Kick'}
nidokingLevelUpMoves = {23:'Thrash'}
clefairyLevelUpMoves = {1:'Pound',1:'Growl',13:'Sing',18:'Doubleslap',24:'Minimize',31:'Metronome',39:'Defense Curl',48:'Light Screen'}
clefableLevelUpMoves = {}
vulpixLevelUpMoves = {1:'Ember',1:'Tail Whip',16:'Quick Attack',21:'Roar',28:'Confuse Ray',35:'Flamethrower',42:'Fire Spin'}
ninetalesLevelUpMoves = {}
jigglypuffLevelUpMoves = {1:'Sing',9:'Pound',14:'Disable',19:'Defense Curl',24:'Doubleslap',29:'Rest',34:'Body Slam',39:'Double Edge'}
wigglytuffLevelUpMoves = {}
zubatLevelUpMoves = {1:'Leech Life',10:'Supersonic',15:'Bite',21:'Confuse Ray',28:'Wing Attack',36:'Haze'}
golbatLevelUpMoves = {32:'Wing Attack',43:'Haze'}
oddishLevelUpMoves = {1:'Absorb',15:'Poison Powder',17:'Stun Spore',19:'Sleep Powder',24:'Acid',33:'Petal Dance',46:'Solar Beam'}
gloomLevelUpMoves = {28:'Acid',38:'Petal Dance',52:'Solar Beam'}
vileplumeLevelUpMoves = {}
parasLevelUpMoves = {1:'Scratch',13:'Stun Spore',20:'Leech Life',27:'Spore',34:'Slash',41:'Growth'}
parasectLevelUpMoves = {30:'Spore',39:'Slash',48:'Growth'}
venonatLevelUpMoves = {1:'Tackle',1:'Disable',24:'Poison Powder',27:'Leech Life',30:'Stun Spore',35:'Psybeam',38:'Sleep Powder',43:'Psychic'}
venomothLevelUpMoves = {38:'Psybeam',43:'Sleep Powder',50:'Psychic'}
diglettLevelUpMoves = {1:'Scratch',15:'Growl',19:'Dig',24:'Sand Attack',31:'Slash',40:'Earthquake'}
dugtrioLevelUpMoves = {35:'Slash',47:'Earthquake'}
meowthLevelUpMoves = {1:'Scratch',1:'Growl',12:'Bite',17:'Pay Day',24:'Screech',33:'Fury Swipes',44:'Slash'}
persianLevelUpMoves = {37:'Fury Swipes',51:'Slash'}
psyduckLevelUpMoves = {1:'Scratch',28:'Tail Whip',31:'Disable',36:'Confusion',43:'Fury Swipes',52:'Hydro Pump'}
golduckLevelUpMoves = {39:'Confusion',48:'Fury Swipes',59:'Hydro Pump'}
mankeyLevelUpMoves = {1:'Scratch',1:'Leer',15:'Karate Chop',21:'Fury Attack',27:'Focus Energy',33:'Seismic Toss',39:'Thrash'}
primeapeLevelUpMoves = {37:'Seismic Toss',46:'Thrash'}
growlitheLevelUpMoves = {1:'Bite',1:'Roar',18:'Ember',23:'Leer',30:'Take Down',39:'Agility',50:'Flamethrower'}
arcanineLevelUpMoves = {}
poliwagLevelUpMoves = {1:'Bubble',16:'Hypnosis',19:'Water Gun',25:'Doubleslap',31:'Body Slam',38:'Amnesia',45:'Hydro Pump'}
poliwhirlLevelUpMoves = {26:'Doubleslap',33:'Body Slam',41:'Amnesia',49:'Hydro Pump'}
poliwrathLevelUpMoves = {}
abraLevelUpMoves = {1:'Teleport'}
kadabraLevelUpMoves = {1:'Teleport',1:'Confusuon',20:'Disable',27:'Psybeam',31:'Recover',38:'Psychic',42:'Reflect'}
alakazamLevelUpMoves = {20:'Disable',27:'Psybeam',31:'Recover',38:'Psychic',42:'Reflect'}
machopLevelUpMoves = {1:'Karate Chop',20:'Low Kick',25:'Leer',32:'Focus Energy',39:'Seismic Toss',46:'Submission'}
machokeLevelUpMoves = {36:'Focus Energy',44:'Seismic Toss',52:'Submission'}
machampLevelUpMoves = {36:'Focus Energy',44:'Seismic Toss',52:'Submission'}
bellsproutLevelUpMoves = {1:'Vine Whip',1:'Growth',13:'Wrap',15:'Poison Powder',18:'Sleep Powder',21:'Stun Spore',26:'Acid',33:'Razor Leaf',42:'Slam'}
weepinbellLevelUpMoves = {23:'Stun Spore',29:'Acid',38:'Razor Leaf',49:'Slam'}
victreebelLevelUpMoves = {}
tentacoolLevelUpMoves = {1:'Acid',7:'Supersonic',13:'Wrap',18:'Poison Sting',22:'Water Gun',27:'Constrict',33:'Barrier',40:'Screech',48:'Hydro Pump'}
tentacruelLevelUpMoves = {35:'Barrier',43:'Screech',50:'Hydro Pump'}
geodudeLevelUpMoves = {1:'Tackle',11:'Defense Curl',16:'Rock Throw',21:'Self Destruct',26:'Harden',31:'Earthquake',36:'Explosion'}
gravelerLevelUpMoves = {29:'Harden',36:'Earthquake',43:'Explosion'}
golemLevelUpMoves = {29:'Harden',36:'Earthquake',43:'Explosion'}
ponytaLevelUpMoves = {1:'Ember',30:'Tail Whip',32:'Stomp',35:'Growl',39:'Fire Spin',43:'Take Down',48:'Agility'}
rapidashLevelUpMoves = {47:'Take Down',55:'Agility'}
slowpokeLevelUpMoves = {1:'Confusion',18:'Disable',22:'Head Butt',27:'Growl',33:'Water Gun',40:'Amnesia',48:'Psychic'}
slowbroLevelUpMoves = {44:'Amnesia',55:'Psychic'}
magnemiteLevelUpMoves = {1:'Tackle',21:'Sonic Boom',25:'Thundershock',29:'Supersonic',35:'Thunder Wave',41:'Swift',47:'Screech'}
magnetonLevelUpMoves = {38:'Thunder Wave',46:'Swift',54:'Screech'}
farfetchdLevelUpMoves = {1:'Peck',1:'Sand Attack',7:'Leer',15:'Fury Attack',23:'Swords Dance',31:'Agility',39:'Slash'}
doduoLevelUpMoves = {1:'Peck',20:'Growl',24:'Fury Attack',30:'Drill Peck',36:'Rage',40:'Tri Attack',44:'Agility'}
dodrioLevelUpMoves = {39:'Rage',45:'Tri Attack',51:'Agility'}
seelLevelUpMoves = {1:'Head Butt',30:'Growl',35:'Aurora Beam',40:'Rest',45:'Take Down',50:'Ice Beam'}
dewgongLevelUpMoves = {35:'Aurora Beam',44:'Rest',50:'Take Down',56:'Ice Beam'}
grimerLevelUpMoves = {1:'Pound',1:'Disable',30:'Poison Gas',33:'Minimize',37:'Sludge',42:'Harden',48:'Screech',55:'Acid Armor'}
mukLevelUpMoves = {45:'Harden',53:'Screech',60:'Acid Armor'}
shellderLevelUpMoves = {1:'Tackle',1:'Withdraw',18:'Supersonic',23:'Clamp',30:'Aurora Beam',39:'Leer',50:'Ice Beam'}
cloysterLevelUpMoves = {50:'Spike Cannon'}
gastlyLevelUpMoves = {1:'Lick',1:'Confuse Ray',1:'Night Shade',27:'Hypnosis',35:'Dream Eater'}
haunterLevelUpMoves = {29:'Hypnosis',38:'Dream Eater'}
gengarLevelUpMoves = {29:'Hypnosis',38:'Dream Eater'}
onixLevelUpMoves = {1:'Tackle',1:'Screech',15:'Bind',19:'Rock Throw',25:'Rage',33:'Slam',43:'Harden'}
drowzeeLevelUpMoves = {1:'Pound',1:'Hypnosis',12:'Disable',17:'Confusion',24:'Head Butt',29:'Poison Gas',32:'Psychic',37:'Meditate'}
hypnoLevelUpMoves = {33:'Poison Gas',37:'Psychic',43:'Meditate'}
krabbyLevelUpMoves = {1:'Bubble',1:'Leer',20:'Vice Grip',25:'Guillotine',30:'Stomp',35:'Crab Hammer',40:'Harden'}
kinglerLevelUpMoves = {34:'Stomp',42:'Crab Hammer',49:'Harden'}
voltorbLevelUpMoves = {1:'Tackle',1:'Screech',17:'Sonic Boom',22:'Self Destruct',29:'Light Screen',36:'Swift',43:'Explosion'}
electrodeLevelUpMoves = {40:'Swift',50:'Explosion'}
exeggcuteLevelUpMoves = {1:'Barrage',1:'Hypnosis',25:'Reflect',28:'Leech Seed',32:'Stun Spore',37:'Poison Powder',42:'Solar Beam',48:'Sleep Powder'}
exeggutorLevelUpMoves = {28:'Stomp'}
cuboneLevelUpMoves = {1:'Bone Club',1:'Growl',25:'Leer',31:'Focus Energy',38:'Thrash',43:'Bonemerang',46:'Rage'}
marowakLevelUpMoves = {33:'Focus Energy',41:'Thrash',48:'Bonemerang',55:'Rage'}
hitmonleeLevelUpMoves = {1:'Double Kick',1:'Meditate',33:'Rolling Kick',38:'Jump Kick',43:'Focus Energy',48:'Hi Jump Kick',53:'Mega Kick'}
hitmonchanLevelUpMoves = {1:'Comet Punch',1:'Agility',33:'Fire Punch',38:'Ice Punch',43:'Thunder Punch',48:'Mega Punch',53:'Counter'}
lickitungLevelUpMoves = {1:'Wrap',1:'Supersonic',7:'Stomp',15:'Disable',23:'Defense Curl',31:'Slam',39:'Screech'}
koffingLevelUpMoves = {1:'Tackle',1:'Smog',32:'Sludge',37:'Smoke Screen',40:'Self Destruct',45:'Haze',48:'Explosion'}
weezingLevelUpMoves = {39:'Smoke Screen',43:'Self Destruct',49:'Haze',53:'Explosion'}
rhyhornLevelUpMoves = {1:'Horn Attack',30:'Stomp',35:'Tail Whip',40:'Fury Attack',45:'Horn Drill',50:'Leer',55:'Take Down'}
rhydonLevelUpMoves = {48:'Horn Drill',55:'Leer',64:'Take Down'}
chanseyLevelUpMoves = {1:'Pound',1:'Doubleslap',24:'Sing',30:'Growl',38:'Minimize',44:'Defense Curl',48:'Light Screen',54:'Double Edge'}
tangelaLevelUpMoves = {1:'Constrict',1:'Bind',29:'Absorb',32:'Poison Powder',36:'Stun Spore',39:'Sleep Powder',45:'Slam',49:'Growth'}
kangaskhanLevelUpMoves = {1:'Comet Punch',1:'Rage',26:'Bite',31:'Tail Whip',36:'Mega Punch',41:'Leer',46:'Dizzy Punch'}
horseaLevelUpMoves = {1:'Bubble',19:'Smoke Screen',24:'Leer',30:'Water Gun',37:'Agility',45:'Hydro Pump'}
seadraLevelUpMoves = {41:'Agility',52:'Hydro Pump'}
goldeenLevelUpMoves = {1:'Peck',1:'Tail Whip',19:'Supersonic',24:'Horn Attack',30:'Fury Attack',37:'Waterfall',45:'Horn Drill',54:'Agility'}
seakingLevelUpMoves = {39:'Waterfall',48:'Horn Drill',54:'Agility'}
staryuLevelUpMoves = {1:'Tackle',17:'Water Gun',22:'Harden',27:'Recover',32:'Swift',37:'Minimize',42:'Light Screen',47:'Hydro Pump'}
starmieLevelUpMoves = {}
mrMimeLevelUpMoves = {1:'Confusion',1:'Barrier',23:'Light Screen',31:'Doubleslap',39:'Meditate',47:'Substitute'}
scytherLevelUpMoves = {1:'Quick Attack',17:'Leer',20:'Focus Energy',24:'Double Team',29:'Slash',35:'Swords Dance',42:'Agility'}
jynxLevelUpMoves = {1:'Pound',1:'Lovely Kiss',15:'Sing',23:'Doubleslap',31:'Ice Punch',39:'Meditate',47:'Blizzard'}
electabuzzLevelUpMoves = {1:'Quick Attack',1:'Leer',34:'Thundershock',37:'Screech',42:'Thunder Punch',49:'Light Screen',54:'Thunder'}
magmarLevelUpMoves = {1:'Ember',36:'Leer',39:'Confuse Ray',43:'Fire Punch',48:'Smoke Screen',52:'Smog',55:'Flamethrower'}
pinsirLevelUpMoves = {1:'Vicegrip',25:'Seismic Toss',30:'Guillotine',36:'Focus Energy',43:'Harden',49:'Slash',54:'Swords Dance'}
taurosLevelUpMoves = {1:'Tackle',21:'Stomp',28:'Tail Whip',35:'Leer',44:'Rage',51:'Take Down'}
magikarpLevelUpMoves = {1:'Splash',15:'Tackle'}
gyaradosLevelUpMoves = {20:'Bite',25:'Dragon Rage',32:'Leer',41:'Hydro Pump',52:'Hyper Beam'}
laprasLevelUpMoves = {1:'Water Gun',1:'Growl',16:'Sing',20:'Mist',25:'Body Slam',31:'Confuse Ray',38:'Ice Beam',46:'Hydro Pump'}
dittoLevelUpMoves = {1:'Transform'}
eeveeLevelUpMoves = {1:'Tackle',1:'Sand Attack',27:'Quick Attack',31:'Tail Whip',37:'Bite',45:'Take Down'}
vaporeonLevelUpMoves = {27:'Quick Attack',31:'Water Gun',37:'Tail Whip',40:'Bite',42:'Acid Armor',44:'Haze',48:'Mist',54:'Hydro Pump'}
jolteonLevelUpMoves = {27:'Quick Attack',31:'Thundershock',37:'Tail Whip',40:'Thunder Wave',42:'Double Kick',44:'Agility',48:'Pin Missile',54:'Thunder'}
flareonLevelUpMoves = {27:'Quick Attack',31:'Ember',37:'Tail Whip',40:'Bite',42:'Leer',44:'Fire Spin',48:'Rage',54:'Flamethrower'}
porygonLevelUpMoves = {1:'Tackle',1:'Sharpen',1:'Conversion',23:'Psybeam',28:'Recover',35:'Agility',42:'Tri Attack'}
omanyteLevelUpMoves = {1:'Water Gun',1:'Withdraw',34:'Horn Attack',39:'Leer',46:'Spike Cannon',53:'Hydro Pump'}
omastarLevelUpMoves = {44:'Spike Cannon',49:'Hydro Pump'}
kabutoLevelUpMoves = {1:'Scratch',1:'Harden',34:'Absorb',39:'Slash',44:'Leer',49:'Hydro Pump'}
kabutopsLevelUpMoves = {46:'Leer',53:'Hydro Pump'}
aerodactylLevelUpMoves = {1:'Wing Attack',1:'Agility',33:'Supersonic',38:'Bite',45:'Take Down',54:'Hyper Beam'}
snorlaxLevelUpMoves = {1:'Head Butt',1:'Amnesia',1:'Rest',35:'Body Slam',41:'Harden',48:'Double Edge',56:'Hyper Beam'}
articunoLevelUpMoves = {1:'Peck',1:'Ice Beam',51:'Blizzard',55:'Agility',60:'Mist'}
zapdosLevelUpMoves = {1:'Thundershock',1:'Drill Peck',51:'Thunder',55:'Agility',60:'Light Screen'}
moltresLevelUpMoves = {1:'Peck',1:'Fire Spin',51:'Leer',55:'Agility',60:'Sky Attack'}
dratiniLevelUpMoves = {1:'Wrap',1:'Leer',10:'Thunder Wave',20:'Agility',30:'Slam',40:'Dragon Rage',50:'Hyper Beam'}
dragonairLevelUpMoves = {35:'Slam',45:'Dragon Rage',55:'Hyper Beam'}
dragoniteLevelUpMoves = {60:'Hyper Beam'}
mewtwoLevelUpMoves = {1:'Confusion',1:'Disable',1:'Swift',63:'Barrier',66:'Psychic',70:'Recover',75:'Mist',81:'Amnesia'}
mewLevelUpMoves = {1:'Pound',10:'Transform',20:'Mega Punch',30:'Metronome',40:'Psychic'}